name: Docker Image for PostgreSQL
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [aws_s3, mount-s3]

    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@v3
      - name: 'Login to Github container registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{secrets.GHCR_USER_NAME}}
          password: ${{secrets.GHCR_USER_PAT}}
      - name: Build the Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.version }}/
          tags: ${{ vars.IMAGE_NAME }}:${{ matrix.version }}
          platforms: linux/amd64
          push: true
  